console.log('I am linked now!');
let name = "Karim";
function myFunction() {
    alert(name);
}
var age1 = 22;
var lastName1 = "Doe";
var DOB1 = "17-8-2023";
let age2 = 22;
let lastName2 = "Doe";
let DOB2 = "17-8-2023";
const age3 = 22;
const lastName3 = "Doe";
const DOB3 = "17-8-2023";
console.log(age1, lastName1, DOB1);
console.log(age2, lastName2, DOB2);
console.log(age3, lastName3, DOB3);
let txt = "This is a text";
let bool1 = true;
let bool2 = false;
let number1 = 1215;
let str1 = "999";
let brackets = {};
let squarebracket = [];
let nul1 = null;
let undef = undefined;
console.log(txt +' '+  typeof txt);
console.log(bool1  +' '+  typeof bool1);
console.log(bool2  +' '+  typeof bool2);
console.log(number1 +' '+ typeof number1);
console.log(str1 +' '+ typeof str1);
console.log(brackets +' '+ typeof brackets);
console.log(squarebracket +' '+ typeof squarebracket);
console.log(nul1 +' '+ nul1);
console.log(undef +' '+ undef);